modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL="https://github.com/petrolpark/Create-Library/issues/10"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.modrinth.com/mod/Petrols-Parts"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''
#enumExtensions="META-INF/enumextensions.json"

[[mixins]]
config="${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
	modId="create"
	type="required"
	versionRange="[6.0.4,7.0.0)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.${mod_id}]]
	modId="petrolpark"
	type="required"
	versionRange="[1.4.7,1.5.0)"
	ordering="AFTER"
	side="BOTH"